apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: default
spec:
  containers: # multiple containers in one pod
  - name: busybox
    image: busybox
    command: 
      - sleep
      - "3600"
  - name: nginx
    image: nginx