apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    app: myapp
    type: front-end
spec:
  # this is from pod-definition.yaml
  replicas: 3
  template:
    metadata:
      name: my-Pod
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest